### ISSUE TITLE
[Feature suggestion] Implement non-ILP algorithm for welfare maximization

### ISSUE THREAD

**Issue by DominikPeters** [COMSOC-Community/pabutools#9]
At the moment, the [max welfare](https://github.com/pbvoting/pabutools/blob/main/pabutools/rules/maxwelfare.py) rule is implemented by an ILP. But one could also solve it using a dynamic program. This could be helpful for controlling the tie-breaking. In addition, I'm too lazy to include an ILP solver in my [pref.tools version](https://pref.tools/pabutools), so for that a pure python approach would also be useful.

(I don't think it's urgent, but it could be a student task.)

**Comment by Simon-Rey** [comment]
Yes, I agree with that!

**Comment by Simon-Rey** [comment]
Btw, what about simply using the Google OR tools? https://developers.google.com/optimization/reference/python/algorithms/pywrapknapsack_solver#knapsack_multidimension_branch_and_bound_solver

**Comment by Simon-Rey** [comment]
A primal/dual approach has now been implemented: https://pbvoting.github.io/pabutools/usage/rules.html#additive-utilitarian-welfare-maximiser by Stefan Haas.

**Comment by Simon-Rey** [comment]
Let me know if you need more @DominikPeters. It currently does not support irresolute outcomes.
